version: '2.3'

volumes: mmx-data

services:
 mmx:
    image: ghcr.io/pestotoast/mmx-node
    restart: always
    container_name: mmx-node
    group_add:
      - 109
      - video
    devices:
      - /dev/dri:/dev/dri
    #entrypoint: /mmx-node/run_node.sh --timelord 0
    volumes:
      - /mnt/plots:/mnt/plots:ro
      - ./data/mmx/testnet3:/mmx-node/testnet3
      - ./config/mmx:/mmx-node/config/local
      - ./data/mmx/wallet.dat:/mmx-node/wallet.da
